version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO: cicd-demo
    LAMBDA_NAME: cicd-demo
    ECR_URI: 277894851352.dkr.ecr.us-east-1.amazonaws.com

phases:

  pre_build:
    commands:
      - echo "Login to ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "Build Docker image"
      - docker build -t $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI/$ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo "Push image to ECR"
      - docker push $ECR_URI/$ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo "Deploy to Lambda"
      - aws lambda update-function-code \
        --function-name $LAMBDA_NAME \
        --image-uri $ECR_URI/$ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION