version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REGISTRY: 277894851352.dkr.ecr.us-east-1.amazonaws.com
    IMAGE_REPO_NAME: cicd-demo
    LAMBDA_FUNCTION: cicd-demo

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR"
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image"
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REGISTRY/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker image to ECR"
      - docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION --image-uri $ECR_REGISTRY/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION